### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by CaptainEven** [ruinmessi/RFBNet#67]
ImportError: /mnt/diskc/even/Car_DR/RFBNet/utils/pycocotools/_mask.so: undefined symbol: _Py_ZeroStruct

**Comment by ruinmessi** [comment]
@CaptainEven  You may re-complie the coco tools using python3

**Comment by CaptainEven** [comment]
@ruinmessi How to compile coco tools?

**Comment by ruinmessi** [comment]
@CaptainEven  Please refer README and make.sh for more details.

**Comment by CaptainEven** [comment]
@ruinmessi I modify python to python3(both python2 and python3 in the rnvironment) in make.sh, and the result is ok now.

**Comment by seongkyun** [comment]
I've got the same error.
The better way to solve this problem is, just install cocoAPI Python version.
And copy and paste the folder inside of the cocoAPI folder named 'pycocotools' to the needed folder, like 'utils' folder in this repository. 

Then all the problems are gone when you face the problem with 'pycocotools' error.
